replicaCount: 2

image:
  repository: 251478238826.dkr.ecr.ap-south-2.amazonaws.com/payment-service
  tag: "21"
  pullPolicy: Always
  
service:
  type: LoadBalancer    # was ClusterIP
  port: 80
  targetPort: 5000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

livenessProbe:
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 15

readinessProbe:
  path: /ready
  initialDelaySeconds: 5
  periodSeconds: 10
